### ISSUE TITLE
Source link renders with empty href

### ISSUE THREAD

**Issue by Macrofig** [bitovi/documentjs#101]
On generated documentation pages, the source link href is empty.

![image](https://cloud.githubusercontent.com/assets/2633542/5993570/8dd70c12-aa23-11e4-92ea-f845ee6d5d92.png)

It looks like the helper for the source link is expecting a `sites.docs.package.repository` property in the `docConfig`. The object here is then supposed to have the github repository base url and version.

I'm guessing that we're just missing some logic in [`make_final_doc_config.js`](https://github.com/bitovi/documentjs/blob/master/lib/configured/make_final_doc_config.js) that extracts this from the `docConfig` and adds it to each `siteConfig` object.

If I'm wrong, and this property needs to be added manually in `documentjs.json`, then will need to update documentation on documentjs site. If so, than I think the source link should only show up if `project` exists in the `siteConfig`.

**Comment by Guamaso** [comment]
It may also be possible that https://github.com/bitovi/documentjs/blob/master/lib/generators/html/build/make_default_helpers.js#L421
is looking for the current version's source in the config somewhere. Could be `config.pageConfig`?

**Comment by justinbmeyer** [comment]
The source link needs to be rethought a bit.  It should come from the project info.  However, I'm not sure if the page gets this information.

**Comment by Guamaso** [comment]
Using [these](http://documentjs.com/docs/DocumentJS.guides.configuring.html) instructions, I was able to build with the correct source link. But only using `version`; not the local working copy. Obviously, because there isn't a source to point to using just the local copy.

So, I think using `config.pageConfig.project` will work as long as the source link is only displayed when `config.pageConfig.project.source` isn't undefined.

For the local copy, though, I was thinking that `projectConfig` can take the project URL and the helper could build the link. But the link would point to the default branch. Ideally, we should be able to detect the origin branch and build the link with that... but that feels excessive. Probably makes more sense to just hide the source link on local builds.

**Comment by Guamaso** [comment]
The other option for local copies is to use the fact that people might already be serving up the project with Gulp/Grunt. Passing the path to this server would also work.

**Comment by jandjorgensen** [comment]
Fixed by #102
